name: Build and Deploy PDF

on:
  push:
    branches:
      - master

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Render CV
        run: rendercv render "Dave_Nilosek,_PhD_CV.yaml"
      - name: Save pdf file
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: rendercv_output/Dave_Nilosek,_PhD_CV.pdf
  create_release:
    runs-on: ubuntu-latest
    needs: build_pdf
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: resume
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Resume v${{ github.run_number }}
          files: Dave_Nilosek,_PhD_CV.pdf
          generate_release_notes: true
