name: Build and Deploy PDF

on:
  push:
    branches:
      - master

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Render CV
        run: rendercv render "Dave_Nilosek_CV.yaml"
      - name: Save pdf file
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: rendercv_output/Dave_Nilosek_CV.pdf
  deploy_pdf:
    runs-on: ubuntu-latest
    needs: build_pdf
    steps:
      - name: Get gh pages repo
        uses: actions/checkout@master
        with:
          repository: dnilosek/dnilosek.github.io
          token: ${{secrets.MY_PAT}}
      - name: Pull saved pdf
        uses: actions/download-artifact@master
        with:
          name: resume
      - name: Commit file
        run: |
          git config --local user.email "action.github.com"
          git config --local user.name "GitHub Action"
          git add resume.pdf
          git commit -m "Pushed by GitHub Action" -a
          git push origin master
